# Configuration file for Octavo

# Deployment text for the document, telling the reader about other versions
deploymentText:
  head:          "This document is available in"

# Document settings (these can be overriden in the Yaml of the Markdown file itself)
# (Note: Some variables must be set in the Yaml itself
# in order to be available to Pandoc and filters)
includedir:       "$octavoPath/includes"                                  # Location of text files to be inserted dynamically
deployconfig:     "$octavoPath/deployConfig"                              # Location of deployment methods (e.g. Pandoc, Say)
remoteserver:     "cccupsychology.com"                                    # Remote server (have this in your .netrc file)
ftpuser:          "cccupsyc"
macosintegration: true

# Edward Tufte style, solarised document

template0: "octavoTufteSolarisedPdf" 
  name: "standard dark theme PDF"
  templateextension: ".tex"
  format: "pdf"
  executable: "pandoc"
    arguments:
      - "--latex-engine=xelatex"
        filters:
          - "filterPopout.py"
          - "filterKeyword.py"
          - "filterDo.py"
          - "filterDivToTufte.py"
          - "pandoc-crossref"
          - "pandoc-citeproc"
          - "pandoc-csv2table"

# Edward Tufte style, document

template1: "octavoTuftePdf"
  name: "standard PDF"
  templateextension: ".tex"
  format: "pdf"
  executable: "pandoc"
    arguments:
      - "--latex-engine=xelatex"
        filters:
          - "filterPopout.py"
          - "filterKeyword.py"
          - "filterDo.py"
          - "filterDivToTufte.py"
          - "pandoc-csv2table"
          - "pandoc-crossref"
          - "pandoc-citeproc"



# Edward Tufte style, book

template2: "octavoTufteBookPdf"
  name: "standard book PDF"
  templateextension: ".tex"
  format: "pdf"
  executable: "pandoc"
    arguments:
      - "--latex-engine=xelatex"
        filters:
          - "filterPopout.py"
          - "filterKeyword.py"
          - "filterDo.py"
          - "filterDivToTufte.py"
          - "pandoc-crossref"
          - "pandoc-citeproc"
          - "pandoc-csv2table"



# Simple Pdf 

template3: "octavoNormalPdf"
  name: "simplified Layout PDF"
  templateextension: ".tex"
  format: "pdf"
  executable: "pandoc"
    arguments:
      - "--latex-engine=xelatex"
        filters:
          - "filterPopout.py"
          - "filterKeyword.py"
          - "filterDo.py"
          - "filterDivToTufte.py"
          - "pandoc-crossref"
          - "pandoc-citeproc"
          - "pandoc-csv2table"


# Large Pdf 

template4: "octavoLargePdf"
  name: "simplified layout PDF with large text"
  templateextension: ".tex"
  format: "pdf"
  executable: "pandoc"
    arguments:
      - "--latex-engine=xelatex"
        filters:
          - "filterDivToTufte.py"
          - "pandoc-crossref"
          - "pandoc-citeproc"
          - "pandoc-csv2table"


# Simplified Pdf with Open Dyslexic 

template5: "octavoOpenDyslexicPdf"
  name: "simplified PDF with Open Dyslexic font"
  templateextension: ".tex"
  format: "pdf"
  executable: "pandoc"
    arguments:
      - "--latex-engine=xelatex"
        filters:
          - "filterDivToTufte.py"
          - "pandoc-crossref"
          - "pandoc-citeproc"
          - "pandoc-csv2table"


# Webpage 

template6: "octavoHtml"
  name: "webpage"
  templateextension: ".html"
  format: "html"
  executable: "pandoc"
    arguments:
      - "--mathml"
      - "--self-contained"
      - "--toc"
      - "--css $octavoPath/templates/octavoHtmlTufte.css"
      - "--latex-engine=xelatex"
        filters:
          - "filterDivToHtml.py"
          - "pandoc-crossref"
          - "pandoc-citeproc"
          - "pandoc-csv2table"


# Microsoft Word Document 

template7: "octavoDocx"
  name: "Microsoft Word format"
  format: "docx"
  executable: "pandoc"
    arguments:
      - "--latex-engine=xelatex"
        filters:
          - "pandoc-crossref"
          - "pandoc-citeproc"
          - "pandoc-csv2table"


# Spoken 

template8: "octavoSpokenMacOs" # This is not a filename, but a special class handled by Octavo.sh
  name: "spoken format"
  format: "mp4"
  executable: "pandoc"
    arguments:
      - ""
        filters:
          - "filterDivToLatex.py"
          - "pandoc-crossref"
          - "pandoc-citeproc"
          - "pandoc-csv2table"


#   executable1: "pandoc"
#     arguments:
#       - "-f html"
#       - "-t plain"
#   executable2: "sed"
#     arguments:
#       - "sed 's/_//g; s/↩//g'"
#   executable: "say"
#     arguments:
#       - "--voice='Alex'"
#       - "--quality=127"
#       - "--file-format='mp4f'"

