# Configuration file for Octavo

# Deployment text for the document, telling the reader about other versions
deploymentText:
  Head:          "This document is available in"
  Body:          ""
  Foot:          "This document contains hyperlinks to [sections within it](#overview), [external webpages](http://cccupsychology.com), and email addresses like [ian.hocking@canterbury.ac.uk](mailto:ian.hocking@canterbury.ac.uk)."

# Location of skeleton files for creation of new Octavo documents
skeletondir:    "$OCTAVOPATH/skeletons"

# Document settings (these can be overriden in the Yaml of the Markdown file itself)
# (Note: Some variables must be set in the Yaml itself
# in order to be available to Pandoc and filters)
crossrefYaml:  "$OCTAVOPATH/includes/pandoc-crossrefSettings.yaml"
includedir:    "$OCTAVOPATH/includes"                                 # Location of text files to be inserted dynamically
templatedir:   "$OCTAVOPATH/templates"                               # Location of templates (Latex, html, etc.)
deployconfig:  "$OCTAVOPATH/deployConfig"                           # Location of deployment methods (e.g. Pandoc, Say)
remoteserver:  "cccupsychology.com"                                 # Remote server (have this in your .netrc file)
