# Edward Tufte style, solarised document

template: "octavoTufteSolarisedPdf" # The template file must be named format.tex
  name: "Standard dark theme PDF"
  format: "pdf"
  executable: "pandoc"
    arguments:
      - "--latex-engine=xelatex"
        filters:
          - "filterPopout.py"
          - "filterKeyword.py"
          - "filterDo.py"
          - "filterDivToTufte.py"

# Edward Tufte style, document

template: "octavoTuftePdf"
  name: "Standard PDF"
  format: "pdf"
  executable: "pandoc"
    arguments:
      - "--latex-engine=xelatex"
        filters:
          - "filterPopout.py"
          - "filterKeyword.py"
          - "filterDo.py"
          - "filterDivToTufte.py"


# Edward Tufte style, book

template: "octavoTufteBookPdf"
  name: "Standard book PDF"
  format: "pdf"
  executable: "pandoc"
    arguments:
      - "--latex-engine=xelatex"
        filters:
          - "filterPopout.py"
          - "filterKeyword.py"
          - "filterDo.py"
          - "filterDivToTufte.py"


# Simple Pdf 

template: "octavoNormalPdf"
  name: "Simplified Layout Pdf"
  format: "pdf"
  executable: "pandoc"
    arguments:
      - "--latex-engine=xelatex"
        filters:
          - "filterPopout.py"
          - "filterKeyword.py"
          - "filterDo.py"
          - "filterDivToTufte.py"

# Large Pdf 

template: "octavoLargePdf"
  name: "Simplified Layout Pdf"
  format: "pdf"
  executable: "pandoc"
    arguments:
      - "--latex-engine=xelatex"
        filters:
          - "filterPopout.py"
          - "filterKeyword.py"
          - "filterDo.py"
          - "filterDivToTufte.py"

# Simplified Pdf with Open Dyslexic 

template: "octavoOpenDyslexicPdf"
  name: "Simplified Pdf with Open Dyslexic Font"
  format: "pdf"
  executable: "pandoc"
    arguments:
      - "--latex-engine=xelatex"
        filters:
          - "filterPopout.py"
          - "filterKeyword.py"
          - "filterDo.py"
          - "filterDivToTufte.py"

# Webpage 

template: "octavoHtml"
  name: "Simplified Pdf with Open Dyslexic Font"
  format: "html"
  executable: "pandoc"
    arguments:
      - "--mathml"
      - "--self-contained"
      - "--toc"
      - "--css $OCTAVOPATH/templates/octavoHtmlTufte.css"
      - "--latex-engine=xelatex"
        filters:
          - "filterDivToHtml.py"

# Microsoft Word Document 

template: "octavoDocx"
  name: "Microsoft Word format"
  format: "docx"
  executable: "pandoc"
    arguments:
      - "--latex-engine=xelatex"

# Spoken 

template: "octavoSpokenMacOs" # This is not a filename, but a special class handled by Octavo.sh
  name: "spoken format"
  format: "mp4"
  executable: "pandoc"
    filters:
      - "filterDivToLatex.py"
  executablesecond: "pandoc"
    arguments:
      - "-f html"
      - "-t plain"
  executablethird: "sed"
    arguments:
      - "sed 's/_//g; s/↩//g'"
  executablefourth: "say"
    arguments:
      - "--voice='Alex'"
      - "--quality=127"
      - "--file-format='mp4f'"
